'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Instrument_Sans } from 'next/font/google'
import { cn } from '@/lib/utils'
import { UserDetailsProvider } from '@/hooks/useUserData'

const instrument_sans = Instrument_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(instrument_sans.className, "bg-background")}>
        
        <UserDetailsProvider>
        {children}
        </UserDetailsProvider>
        </body>
    </html>
  )
}
